### ISSUE TITLE
After some times of connection on a muc, this one consider me to be not any more an occupant

### ISSUE THREAD

**Issue by Trim** [maranda/metronome#194]
This happens when I connect with my Metronome account on other chatrooms like. movim@conference.movim.eu and swisslinux@chat.swisslinux.org.

Here, you'll find a paste from gajim client which tried to send "!who" to swisslinux chatroom:

https://pbin.adorsaz.ch/?202fa0601824ddd7#iJNbc8IgHuq/s+WbADlv6oYfQ/G2xodED+CN6fbJuyM=

Does this error come from my xmpp client or from my Metronome server ?

**Comment by Trim** [comment]
I've just got a bit more information about my issue. The swisslinux chatroom administrator said I was automatically banned with this message:

> (This participant is kicked from the room because he sent an error presence: remote-server-not-found)

So it seems to be an error because of my firewall as I thought.

**Comment by Trim** [comment]
OK, the admin chatroom said me it seems more to be this situation:

1. my client (Gajim v0.16) connect to the chatroom without issue
2. then it checks connection with other participants and remarks that one can't be resolved
3. so it sends to the chatroom "remote-server-not-found" and then the chatroom kicks me

I've noticed too, that one of these participant were inside my contact list and had the error noticed "Server-to-server connection failed: connection time-out" (in fact, this contact is the chatroom admin mentioned before). So with such error I've checked my metronome's log and I've seen that:

> Jan 08 12:26:36 s2sout86eceb0   info    Beginning new connection attempt to jabber.sebseb01.net ([46.226.111.162]:5269)
> Jan 08 12:26:36 s2sout86eceb0   info    sent dialback key on outgoing s2s stream
> Jan 08 12:26:47 s2sin8566d90    info    Session closed by remote with error: unsupported-stanza-type
> Jan 08 12:26:47 s2sin8566d90    info    incoming s2s stream jabber.sebseb01.net->adorsaz.ch closed: unsupported-stanza-type
> Jan 08 12:27:36 s2sout86eceb0   info    Session closed by remote with error: connection-timeout
> Jan 08 12:27:36 s2sout86eceb0   info    outgoing s2s stream adorsaz.ch->jabber.sebseb01.net closed: connection-timeout
> Jan 08 12:27:36 s2sout86eceb0   info    sending error replies for 1 queued stanzas because of failed outgoing connection to jabber.sebseb01.net
> Jan 08 12:28:24 s2sin8263bc0    info    Session closed by remote with error: unsupported-stanza-type
> Jan 08 12:28:24 s2sin8263bc0    info    incoming s2s stream jabber.sebseb01.net->adorsaz.ch closed: unsupported-stanza-type

I'm actually running Metronome 3.6.20 and I'll update ASAP and I'll try to enable more verbose logs.

**Comment by maranda** [comment]
That's a bug or problem on the remote end, not supporting dialback by the looks.
