### ISSUE TITLE
throttle.lua floor

### ISSUE THREAD

**Issue by Hypher** [maranda/metronome#223]
Hi!
You could be interested in https://github.com/bjc/prosody/issues/6

**Comment by maranda** [comment]
I couldn't replicate the issue described in bjc/prosody#6.

**Comment by Hypher** [comment]
How could you not?
```
	local elapsed = newt - self.t;
	self.t = newt;
	local balance = floor(self.rate * elapsed) + self.balance;
```
If `rate = 1` and `elapsed < 1` (more than one per second), the `t` will be reset and the `balance` wont rise, for the eternity!

**Comment by maranda** [comment]
I'm not sure how you're using util.throttle but no I can't replicate what you're describing because:
* Calling create(1,1) doesn't make sense (to myself at least)
* Max should be always a product of max*period so maybe you wanted create(1,2)
* In the obscure case you do, you can supply a different cost to poll() to adjust that corner case
* Usually rate never ends to be an integer, and in that case see above
* Balance is supposed to be an integer

**Comment by Hypher** [comment]
For instance creating a throttle to allow an user to post 1 message per second, with a burst of 2 messages: `throttle.create(2, 2)` and you got the bug.

But assume you called `throttle.create(1, 2)` you have a rate of 0.5 which is worse:
Calling `update` (or `poll`) more than once per two seconds, balance will never raise. Note that is not a matter of `cost` passed to `poll`, it's just the *frequency* on which you call `update`.

Calling `throttle.create(2, 1)` will produce the same problem with more than two calls per second.

The problem exists. And this is a non-sense that calling `update` could alter the *behavior* of the throttle.
`balance` shoud be a float, or should update `t` in a way to keep extra time not used to fill the balance. Because if you don't do that, you are *dropping* a delta-time and leak the user.

**Comment by maranda** [comment]
It's not so, sorry I just tested this over and over for a hour using muc limits, what you're experiencing *doesn't just happen* period.

Stanzas are coherently blocked within the setting's limits with *whatever frequency* they're sent.

**Comment by Hypher** [comment]
Maybe you didn't understand the problem?

Suppose we want to allow only 15 stanza within 60 seconds in a room, whatever the user that sends them.
`th = throttle.create(15, 60) => { rate=0.25, max=15, t=0, balance=15 }`
The users should post 15 stanza within 60 seconds, with an initial burst of 15 stanzas.
So at least **1 stanza each 4 seconds**.
Now post 15 stanzas to use all your burst to put it in the state `{ t=T0, balance=0 }`
2 seconds later a new stanza is coming, calling `poll` (whatever the `cost` argument value is) will call `update`:
`th:update() => elapsed=2, and floor(0.25 * 2) = floor(0.5) = 0`
So it updates the state to `{ t=T0+2, balance=0 }` and will return `false`.
2 seconds later, same happens:
`th:update() => elapsed=2, and floor(0.25 * 2) = floor(0.5) = 0`
Now the throttle state is again `{ t=T0+4, balance=0 }` and return `false`.
Wait. 4 seconds elapsed and the throttle still refuses to accept stanzas? This violates the rate config of **1 stanza each 4 seconds**!
2 seconds later, same happens:
`th:update() => elapsed=2, and floor(0.25 * 2) = floor(0.5) = 0`
And so on for the eternity...
The users will **never** be allowed to post a stanza. But they *should* be able to post at least **1 stanza each 4 seconds**.

The problem is not that stanza is *correctly blocked*, the problem is that it is *too much blocked*, and that this behavior depends on the `update` call frequency, which is a non-sense. A non expected side-effect.

So in this case, one nasty user sending too much stanza in the room will block the room forever.
Same applies for a community of users, that together produces a frequency giving the `rate*elapsed < 1` problem.
Same applies for a single user trying to speak over that frequency (easy if the frequency is low, as for twitch channels that are limited to 1 message over 30 seconds).

The solution? Just remove the `floor`.
If you want `balance` to always be an integer, don't update `t` if `rate*elapsed < 1`.

**Comment by maranda** [comment]
Good and... That's *working as intended*, once burst is exhausted no one, with possibly given exceptions, is supposed to be able to *send stanzas*.
