### ISSUE TITLE
Metronome fails to daemonize on OpenBSD

### ISSUE THREAD

**Issue by viq** [maranda/metronome#231]
With `daemonize = false` it stays running and listens on ports, without it or with `daemonize = true` it immediately shuts down.

Full ktrace available at https://gist.github.com/viq/56de2bd50bbe951f52da

**Comment by maranda** [comment]
I suppose this could be related to the daemonization code, although not having OpenBSD or another BSD like system or enough confidence with 'em I'm not sure how to find a solution for this.

**Comment by viq** [comment]
I could prepare a Vagrant environment for you to try things in, if that works for you.

**Comment by maranda** [comment]
Having the time to troubleshoot properly it *could* work, I think the problem *could* lie into util.pposix but given how rusty I'm atm at coding I think the task could be above my abilities for the time being.
