### ISSUE TITLE
Add support of "node" when doing a 'disco#items' on PEP

### ISSUE THREAD

**Issue by edhelas** [maranda/metronome#236]
Metronome doesn't handle the `node` parameter when doing a `disco#items` requests.

```
<iq to='user@metronome.server' type='get' id='iJNe3g'>
	<query xmlns='http://jabber.org/protocol/disco#items' node='urn:xmpp:microblog:0'/>
</iq>
<iq id='iJNe3g' type='result' to='user@metronome.server/d6c97876-d219-4a3d-a58d-1ba9c5850e0b' from='user@metronome.server'>
	<query xmlns='http://jabber.org/protocol/disco#items'>
		<item jid='user@metronome.server' node='urn:xmpp:microblog:0:comments/396238f020f2e3ad0485544007518541'/>
		<item jid='user@metronome.server' node='urn:xmpp:microblog:0:comments/233c0fa23839b79779b080e9182beeef'/>
		<item jid='user@metronome.server' node='urn:xmpp:microblog:0:comments/d8afda2a2b0d79b75ea84e2eff537124'/>
	</query>
</iq>
```

Should return something like this (example on ejabberd)

```
<iq to='user@ejabberd.server' type='get' id='iJNe2Cg'>
	<query xmlns='http://jabber.org/protocol/disco#items' node='urn:xmpp:microblog:0'/>
</iq>
<iq id='iJNe2Cg' type='result' to='user@metronome.server/d6c97876-d219-4a3d-a58d-1ba9c5850e0b' from='user@ejabberd.server'>
	<query xmlns='http://jabber.org/protocol/disco#items' node='urn:xmpp:microblog:0'>
		<item jid='user@ejabberd.server' name='c3db1a5b-007d-4a6c-b2bb-a09b32985ecc'/>
		<item jid='user@ejabberd.server' name='df170fac-d3b9-4061-88df-8aec9d3ea95c'/>
	</query>
</iq>
```

**Comment by maranda** [comment]
I'll have to look at the code, it's been a while but the namespace there is urn:xmpp:microblog:0:comments not urn:xmpp:microblog:0, so I'm not sure how is it supposed to eventually handle the node request.

**Comment by edhelas** [comment]
Hi, sorry for the delay, it seems that it should not return urn:xmpp:microblog:0:comments nodes, only the items id of the urn:xmpp:microblog:0 node (like it does for standard Pubsub services).

**Comment by maranda** [comment]
It's the id the items are created with that matters, if you create those with "396238f020f2e3ad0485544007518541" instead of "urn:xmpp:microblog:0:comments/396238f020f2e3ad0485544007518541" Metronome will exactly return that. Doing anything different to specially handle cases doesn't make sense.
