### ISSUE TITLE
XEP-0363 "HTTP File Upload" support

### ISSUE THREAD

**Issue by Sekanato** [maranda/metronome#307]
Is XEP-0363 implementation planned?
Would be nice to send pictures ;)

**Comment by maranda** [comment]
Possibly, but at the moment I'm not particularly enthralled by having Metronome serve files itself with an internal component. Though for sure you could use an external component like https://github.com/guusdk/httpfileuploadcomponent that should work the same way (and possibly better)

**Comment by Sekanato** [comment]
Thanks, I'll look into your suggestion. Maybe external component solution really would be better in this case.

**Comment by maranda** [comment]
And I somehow have the suspect just glancing at the code the module from Prosody Modules (mod_http_upload) could even work without changes

**Comment by maranda** [comment]
Suspected wrong 👎

**Comment by maranda** [comment]
Decided to backport anyways, the one from Prosody modules is well done and could be adapted to work in Metronome quickly.
