### ISSUE TITLE
Fix access model whitelist for #get_items in util.pubsub.

### ISSUE THREAD

**Issue by maranda** [maranda/metronome#355]
There's a mistake in the code that causes the check to never happen.

**Comment by rthouvenin** [comment]
Hey @maranda Is this the problem I've been asking about to you on Jabber (on the same day as when you opened this issue)?
Sorry that I didn't get the chance to get back earlier.

**Comment by rthouvenin** [comment]
Great, thanks for fixing and looking forward to 3.9.
