### ISSUE TITLE
metronomectl status is incorrect

### ISSUE THREAD

**Issue by halars** [maranda/metronome#387]
After running `metronomectl start`, I receive the following:
 
> Still waiting...
> Metronome is still not running. Please give it some time or check your log files for errors

But Metronome is running fine, and this is the output from the log:

> Jun 29 22:45:32 general info    Hello and welcome to Metronome version 3.9.9
> Jun 29 22:45:32 general info    Metronome is using the epoll backend for connection handling
> Jun 29 22:45:32 portmanager     info    Activated service 'c2s'
> Jun 29 22:45:32 portmanager     info    Activated service 'c2s_secure'
> Jun 29 22:45:32 portmanager     info    Activated service 'http'
> Jun 29 22:45:32 portmanager     info    Activated service 'https'
> Jun 29 22:45:32 portmanager     info    Activated service 's2s'
> Jun 29 22:45:32 portmanager     info    Activated service 's2s_secure'
> Jun 29 22:45:32 mod_posix       info    Successfully daemonized to PID 9900
> Jun 29 22:45:40 c2s25a1230      info    Client connected
> Jun 29 22:45:44 c2s25a1230      info    Authenticated as usercl1@localhost

The error log is empty

`metronomectl status`, yield:
> Metronome is not running

But because of this metronome can't be stopped, and `metronomectl start` just spawns another copy.

The system:
Clear Linux 23350, on WSL (4.4.0-17134)

.

**Comment by maranda** [comment]
It sounds like metronomectl can't get a lock on the pidfile, is it readable? Are you running metronomectl with sudo?

**Comment by halars** [comment]
Yes, it is readable, and yes.

**Comment by halars** [comment]
If the metronome user can't create the PID-file (by changing ownership of /var/run/metronome/ in this case), it fails to start.

**Comment by maranda** [comment]
That may happen because metronomectl is either failing to read the pidfile content, or because it isn't locked, try killing Metronome, deleting the pidfile and see what happens.

**Comment by halars** [comment]
It happens every time. And I've tried killing metronome and deleting the pidfile: a new one is created when starting metronome, but the issue persists.
Only using metronomectl.

**Comment by maranda** [comment]
I cannot reproduce, it looks to me that the pid file can't get locked properly. I'll commit a change that specifically reports that case.

**Comment by halars** [comment]
ok, I'll try when updated

**Comment by maranda** [comment]
Sorry for the lateness, but I was away these days and had no time to investigate the issue, try setting in the global config: `metronomectl_timeout = 40`

Report any change, thanks.
