### ISSUE TITLE
Store Passwords Secure

### ISSUE THREAD

**Issue by 6543** [maranda/metronome#390]
Passwords are storet in plain text, is there a option to store only the hash of  it?

**Comment by maranda** [comment]
Passwords are stored in plain text because by default Metronome uses the "internal plain" authentication backend, to store the passwords in hashed format you need to set under the virtualhost section of the host you want to set the backend for:

```lua
authentication = "internal_hashed"
```

**Comment by 6543** [comment]
should we add an commend in the 'metronome.cfg.lua.dist' file?
would be helpful ;)

**Comment by maranda** [comment]
Possibly, but I suppose that best goes into documentation, as far as security is concerned hashed passwords help only in the case of system compromision. And impose some usability limitations that are only justified if you run a non personal service.
