### ISSUE TITLE
Metronome can not change password in client

### ISSUE THREAD

**Issue by cubesky** [maranda/metronome#394]
I load `register` module and set `allow_registration=false;`.  
Then I try to change my password in XMPP Clients (Gajim and Conversations). But they told me can not change password.  
I try to set `allow_registration=true;` But this problem still here.  
I used `authentication = "internal_hashed"`

**Comment by maranda** [comment]
Metronome ensures passwords are of decent strength by default. A password to be valid needs to be at least 8 characters long and contain at least either one number or symbol (and not exceed 30 characters).

**Comment by maranda** [comment]
Either way Metronome sends a human readable error stating that is the issue, if it does not show it that's a problem to be reported to Gajim's devs.

**Comment by cubesky** [comment]
Thank you. I improved password strength and it works!
