### ISSUE TITLE
Http Upload issue

### ISSUE THREAD

**Issue by cubesky** [maranda/metronome#399]
I want to send a video (17M) to a MUC, client says File too large. I have enabled `http_upload` module, it seems  it can not upload big files. I found `mod_http_upload_external` module from prosody, but it doesn't work with metronome. What should I do for this?

**Comment by maranda** [comment]
Just nothing for now Metronome internal HTTP upload as a hard cap limit of 12 MiBs, no way to get it larger. And I'm not sure when I will consider an external alternative.

**Comment by maranda** [comment]
By the way to make it work with Metronome you just need to replace `local http = require "util.http";` with `local http = require "net.http";`

**Comment by maranda** [comment]
And I looked into the issue more closely. while it'd be very easy to backport (as told above) the security bit is a bit concerning as beside the token there's no other protection and if someone ever manages to guess the server secret and/or bruteforce it he'll be able to upload files indiscriminately.

**Comment by cubesky** [comment]
I just replace `util.http` to `net.http` to use mod_http_upload_external. I set a long and complex secret to avoid guessing server secret.
