### ISSUE TITLE
Fail2ban implimentaion 

### ISSUE THREAD

**Issue by anmol26s** [maranda/metronome#462]
Is it possible to have Fail2ban implementation for metronome?

**Comment by maranda** [comment]
In which context? Metronome has mod_gate_guard which implements a concept similar to fail2ban for s2s. For c2s connections fail2ban has little use since by default Metronome enforces the usage of safe passwords and supports SCRAM with channel binding.

**Comment by anmol26s** [comment]
`In which context?`
For yunohost  which have Ldap support for Metronome it don't work. Despite of entering wrong passwords nothing gets blocked. This can be dangerous as successful brute force attack can give access to all the yunohost apps using Ldap.

**Comment by maranda** [comment]
In that case it's the LDAP backend that should perform the fail2ban, not Metronome.

**Comment by maranda** [comment]
I suggest querying the YunoHost people about it, Metronome has just read-only access to that backend.
