### ISSUE TITLE
Add support for XEP-0355

### ISSUE THREAD

**Issue by xmaillard** [maranda/metronome#471]
Hello,

see here for details: https://xmpp.org/extensions/xep-0355.html
Authors of this XEP have already produced a module for Prosody which needs some work to port to Metronome (due to missing dependencies). I have tried myself but at least, it lacks: util.id, util.random and core.rostermanager.
I do not know the core of metronome enough to port it myself.

Notice: https://modules.prosody.im/mod_delegation.html

It needs a small patch to mod_component.lua to fire a new signal (easy to do)

**Comment by maranda** [comment]
I'll need time to check this a bit more but I for now can tell you what to replace:
- Metronome has no util.id, replace its import using `require "util.uuid".generate` instead
- Rostermanager is not in core anymore you can import it using `require "util.rostermanager"` instead
- I see no imports of "util.random", but if it's a call to PRNG that doesn't need to be cryptographically secure you could use math.random instead

**Comment by xmaillard** [comment]
Thanks to your indications, I successfully (and simply) got it working with metronome 3.11.

Here is my file for inclusion (if you wanted to).

[XEP-0355-0356.zip](https://github.com/maranda/metronome/files/2896556/XEP-0355-0356.zip)

**Comment by maranda** [comment]
Closing for now.
