### ISSUE TITLE
Add support for XEP-0356

### ISSUE THREAD

**Issue by xmaillard** [maranda/metronome#472]
Hello,

as for XEP-0355, Prosody has a module for it which should be quite simple to port into Metronome. As I mentioned it in the other issue, there should be missing dependencies.

A link to the Prosody module page: https://modules.prosody.im/mod_privilege.html

Thank you

**Comment by maranda** [comment]
See https://github.com/maranda/metronome/issues/471#issuecomment-466547522

**Comment by xmaillard** [comment]
Fixed in #471 
Closing it
