### ISSUE TITLE
SASL: Error for deactivated account not user friendly

### ISSUE THREAD

**Issue by lovetox** [maranda/metronome#501]
Hi,

- registering at lightwitch.org
- ignore the email activiation

After the account is deactivated the error is

```xml
<failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
    <temporary-auth-failure/>
    <text>Missing sha-256 keys</text>
</failure>
```

I would argue this message is nothing i can show the User

Either use the SASL specific `account-disabled` or a text that a user can understand

**Comment by maranda** [comment]
That message is not related to the account being disabled, that's related to you using SCRAM-SHA-256, and the account's data entry missing related sha-256 server keys, which is solved by changing your account password (it obviously happens on accounts that were created before the implementation)

**Comment by maranda** [comment]
When an account is deleted by the Registration API it'll just delete the account and will prompt a completely different message

**Comment by lovetox** [comment]
But thats not the case, i created the account yesterday, and today i get this message.

But it doesnt matter why this Message comes up, its bad in any circumstance whatsoever

Nobody beside you knows what that means, why send your debug message over the wire to users?

**Comment by maranda** [comment]
I replicated the issue, but it's due to a problem with storagemanager and the flat store not being wiped correctly upon deletion with Lua 5.2. I'll rename the issue accordingly.

**Comment by maranda** [comment]
> But thats not the case, i created the account yesterday, and today i get this message.
> 
> But it doesnt matter why this Message comes up, its bad in any circumstance whatsoever
> 
> Nobody beside you knows what that means, why send your debug message over the wire to users?

lovetox the message does have a sense to be there, the main condition is a Temporary Auth Failure, then again when people report me the server condition I know exactly what to tell 'em to do worked countless times, the fact that I could make it even more descriptive is another matter.

**Comment by lovetox** [comment]
As a developer you where contacted by Admins about that Issue, and they can see that in their debug logs, if they get contacted by their users.

There is absolutely no use to tell a *user*, that some SHA Key is missing, its just not of any interest to them and does not tell them how they can fix the problem.

You may be also a server admin, but normally as a developer you never get in contact with users.

And admins have simply more appropriate tools to see and find the issue (the server debug logs), and don't need to depend on the user telling them some debug message.

So the message should read

`Authentication failed, please contact your admin to resolve the problem`

or

`Authentication failed, please change your password`

So please if you design messages for <text> fields always think from a user point of view, what do i as a user need to read here so i know what to do.

just my 2 cents :)
