### ISSUE TITLE
storage="internal"

### ISSUE THREAD

**Issue by yalh76** [maranda/metronome#505]
I'm currently working on the packaging of jitsi-meet for Yunohost.

for the configuration, here is the configuration provided: 
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example

I'm currently trying to adapt it for YunoHost:
- main metronome config: https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/metronome/metronome.cfg.lua
- jitsi-meet config: https://github.com/YunoHost-Apps/jitsi_ynh/blob/fix_video/conf/metronome.cfg.lua

For the domain auth.myjitsidomain.org, I need to activate `authentication = "internal_plain"`
as seen at: 

https://github.com/jitsi/jitsi-meet/blob/4824c8714aeb35bfa4bd373dbbada018e49dc0e2/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L66-L67

Doing :

https://github.com/YunoHost-Apps/jitsi_ynh/blob/14fee3be31496f855151085030266b01384a47cd/conf/metronome.cfg.lua#L70-L76

In that domain I need to create two users:

https://github.com/jitsi/jitsi-meet/blob/4824c8714aeb35bfa4bd373dbbada018e49dc0e2/debian/jitsi-meet-prosody.postinst#L124-L134

I've done it: 
https://github.com/YunoHost-Apps/jitsi_ynh/blob/14fee3be31496f855151085030266b01384a47cd/scripts/install#L193-L194

But when I test it manually, the user is not created:
`metronomectl adduser focus_user@auth.test11.yh.yalh.net toto`
I have:
```
storagemanager      warn        Falling back to null driver for accounts storage on auth.test11.yh.yalh.net
modulemanager       warn        storage_internal is already loaded for auth.test11.yh.yalh.net, so not loading again
storagemanager      warn        Falling back to null driver for accounts storage on auth.test11.yh.yalh.net
modulemanager       warn        storage_internal is already loaded for auth.test11.yh.yalh.net, so not loading again
storagemanager      warn        Falling back to null driver for accounts storage on auth.test11.yh.yalh.net
modulemanager       warn        storage_internal is already loaded for auth.test11.yh.yalh.net, so not loading again
storagemanager      warn        Falling back to null driver for accounts storage on auth.test11.yh.yalh.net
Server Error: no data storage active
```

What modification I have to do in VirtualHost "auth.__DOMAIN__" to let me create users ?

**Comment by maranda** [comment]
It looks like there's a regression in the metronomectl code, caused by the changes to make Metronome Lua 5.2 compatible, I'll give it a check.
