### ISSUE TITLE
Chat states are not recognized 

### ISSUE THREAD

**Issue by amyspark** [maranda/metronome#514]
I'm getting these errors on Metronome 3.13.5, both on my own server and as replies from lightwitch.org. Client used is Gajim 1.1.3 on Manjaro.

```xml
<!-- Outgoing mié 29 abr 2020 09:46:06 -->
<message xmlns="jabber:client" type="chat" id="ac4a1445-924f-400c-b6c0-176eadca3056" to="hello@example.com" from="world@example.com/gajim">
<gone xmlns="http://jabber.org/protocol/chatstates" />
<no-store xmlns="urn:xmpp:hints" />
</message>

<!-- Outgoing mié 29 abr 2020 09:46:06 -->
<r xmlns="urn:xmpp:sm:3" />

<!-- Incoming mié 29 abr 2020 09:46:06 -->
<message xmlns="jabber:client" type="error" id="ac4a1445-924f-400c-b6c0-176eadca3056" to="world@example.com/gajim" from="hello@example.com">
<error type="cancel">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
</error>
</message>

<!-- Incoming mié 29 abr 2020 09:46:06 -->
<a xmlns="urn:xmpp:sm:3" h="32" />
```
I set up debug logging on the server, but there isn't any stacktrace or error message.

**Comment by maranda** [comment]
It's not that they're recognizing it's that you're sending it to a resource which isn't currently online (that's what the service-unavailable is about).

**Comment by amyspark** [comment]
They were all online at the same time. This error appeared on accounts I was testing with, on the very same client.

**Comment by maranda** [comment]
@amyspark it's a different bug, not related to chatstates actually.
