### ISSUE TITLE
Multi-Session Nicks

### ISSUE THREAD

**Issue by Neustradamus** [maranda/metronome#522]
Can you add Metronome IM informations here:
- https://wiki.xmpp.org/web/Multi-Session_Nicks

**Comment by maranda** [comment]
No I can't, I don't have access

Inviato da Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Neustradamus** [comment]
@maranda: Tell me and I will add :)

**Comment by Neustradamus** [comment]
@maranda: Solved?

**Comment by Neustradamus** [comment]
@maranda: Any news on it?
