### ISSUE TITLE
Problem with authentication = "anonymous"

### ISSUE THREAD

**Issue by kay0u** [maranda/metronome#528]
When I use `authentication = "anonymous"` in my `VirtualHost "kayou.ynh.fr"` section I have a problem during creation of a new user:
Here my config file [/etc/metronome/conf.d/kayou.ynh.fr.cfg.lua](https://paste.yunohost.org/zodidirute.lua)
```
metronomectl adduser test@kayou.ynh.fr test

lua5.1: /usr/lib/metronome/modules/mod_auth_anonymous.lua:41: attempt to index field 'sessions' (a nil value)
stack traceback:
        /usr/lib/metronome/modules/mod_auth_anonymous.lua:41: in function </usr/lib/metronome/modules/mod_auth_anonymous.lua:40>
        (tail call): ?
        /usr/lib/metronome/util/metronomectl.lua:160: in function 'controluser'
        /usr/bin/metronomectl:307: in function '?'
        /usr/bin/metronomectl:812: in main chunk
        [C]: ?
```

**Comment by maranda** [comment]
That's to be expected, you aren't supposed to create users on an anonymous host.

**Comment by maranda** [comment]
Although metronomectl should be more clear about that.
What are you trying to achieve by the way?

**Comment by maranda** [comment]
also if it's for Jitsi Meet you need to replace:
```
muc_room_locking = false
muc_room_default_public_jids = true
```

with:
```
allow_anonymous_creation = true
instant_room_on_creation = true
room_default_config = { whois = "anyone" }
```

On both **conference.kayou.ynh.fr** and **internal.auth.kayou.ynh.fr**

**Comment by kay0u** [comment]
Thank you for your quick answer! I'm just executing random commands and trying to debug Jitsi :-)
