### ISSUE TITLE
Registration is possible in clients that don't show entire form

### ISSUE THREAD

**Issue by mimi89999** [maranda/metronome#530]
Hello,
I noticed that registration is possible from clients that don't show the entire registration form like Conversations or Dino (https://github.com/dino/dino/issues/988). This is an issue because users might register accounts without ever seeing the ToS. I was able to register an account on LW.org in Conversations without seeing the ToS message.

**Comment by maranda** [comment]
That's on purpose you can't use S2S anyways without accepting the terms of service.

**Comment by maranda** [comment]
You should open a ticket with Conversations for not showing the full registration form fields, not with Metronome. I already reported the issue with Daniel and he said that's "by design" that a mobile client shouldn't show extended IBR fields except captcha from eJabberd.

**Comment by mimi89999** [comment]
Even with S2S not available and the account not very usable, you can still collect data such as password, email, IP address, etc. Also, other servers using Metronome might not disable S2S for new accounts. I think that it would be better to add a required boolean field.

**Comment by maranda** [comment]
Everything is covered, GDPR locked accounts can't receive stanzas from external users, when they join MUCs they're appropriately warned. Also from a legal perspective as soon as you registered you're implicitly accepting the ToS, the statement is added to the form it's C who's hiding it (which makes it eventually liable), it's also impossible for the server to query client capabilities during IBR, so I can't know what a client does or doesn't.

**Comment by maranda** [comment]
Also these settings are peculiar to lightwitch.org not Metronome, there's no settings by default that implement terms of service in the registration form, or the GDPR compliance policies, etc.
