### ISSUE TITLE
compatibility with snikket-ios push

### ISSUE THREAD

**Issue by mooseyboots** [maranda/metronome#532]
hi marco/metronome,

snikket recently released an ios app, which got me trying to configure my metronome instance on a yunohost server.

on their announcement blog post (https://snikket.org/blog/snikket-ios-public-release/), they mention a number of prosody community modules being needed to get push notifications working right (cloud_notify variants).

is it possible to enable such modules, made for prosody, on metronome?

also, is it possible to enable the prosody community module "mod_csi_battery_saver"? (i think this makes it possible for incoming a/v calls to wake up a sleeping ios client.)

or if you have any other pointers for such config, i'd be glad to hear them.

thanks.

**Comment by maranda** [comment]
Hi @mooseyboots, all the features you described in Metronome are condensed into two modules:
- mod_push for the PUSH notifications
- mod_stanza_optimizations for CSI

Let me know if you encounter any additional issues.
