### ISSUE TITLE
metronome using all memory

### ISSUE THREAD

**Issue by mooseyboots** [maranda/metronome#536]
hi again,

i'm running metronome on a yunohost install. recently metronome started using large amounts of memory, often to the point where it would cripple my whole server. i'm running it on a 1gb raspberry pi. i have made some mods to the configuration file to add turn/stun server, but that was long before this issue came up. memory doesn't always directly increase, it seems to come in waves. but often it chokes everything until i restart metronome. and when it does not totally choke it, it still seems to be using markedly more than i would expect (it sits at around say 10-15-20 percent in htop)

i haven't found anything in the logs. i asked on the yunohost forum here https://forum.yunohost.org/t/metronome-using-all-available-memory/18666/6 (pasted some logs there), but nothing came up that was helpful.

i wonder if you've seen anything like this before or if you have any suggestion of where/how i might track down the issue? i have run prosody servers for a few years and never seen this happen.

i thought to try switching back to a stock config file to rule out any config changes. i would appreciate avoiding nuking the install if possible, given the user data on there.

**Comment by mooseyboots** [comment]
i tried removing all xmpp config for unneeded subdomains, which didn't help. then i tried removing this config, for A/V calls on the server: https://github.com/YunoHost/issues/issues/1607

if i remove the extdisco and jingle config shown in the first post of that issue, the issue seems to go away.

should that config be resource hungry? i'd like to still have the option to make calls if possible.

**Comment by maranda** [comment]
@mooseyboots are you running Coturn on the same Raspberry Pi as Metronome, because mod_extdisco does nothing beside exposing the related configuration to make a STUN/TURN connection, what I would disable to conserve resource are actually all logging modules e.g. mod_mam and mod_muc_log, mod_muc_log_mam, mod_mam_browser, all those conserve a cache of the archive in RAM and so are pretty much a no go for memory constrained environments.

**Comment by maranda** [comment]
Closing issue as I received no further info on it.
