### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [maranda/metronome#539]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266 

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3 

Thanks in advance.

**Comment by Neustradamus** [comment]
@maranda: Little recall about this ticket ;)

**Comment by maranda** [comment]
Not going to implement channel bindings for 13 for now, don't have the time.

**Comment by Neustradamus** [comment]
@maranda: Please do not close unsolved ticket...
