### ISSUE TITLE
Server compliance to the xmpp im standard blank in the im cathegory?

### ISSUE THREAD

**Issue by yibaba** [maranda/metronome#541]
While browsing the xmpp servers compliance it came to my attention that the im field is empty when given the project's purpose i would have expected at least a core rating [[1]](https://xmpp.org/software/servers/metronome-im/).

Looking at the table [here](https://xmpp.org/extensions/xep-0459.html#im) and the claimed compliance [here](https://metronome.im/supported-xeps-list) and in [1] it seems that XEP-0249, XEP-0402, XEP-0410. Somo of these seem to be client only¿? I don't know enough about xmpp to judge that, but I would like to ask if any of these en up being server applicable XEPs would you be open to implement it/them? Thanks for your time.

**Comment by maranda** [comment]
That's a mistake in the doap file probably, as the site says:
"Metronome currently has Advanced Server compliance for Core, Web, IM and Mobile in XMPP Compliance Suites 2020 (XEP-0423)."

**Comment by yibaba** [comment]
Sorry i don't know which site yo are referring to. Can you link me to it out of curiosity? I'll close after thanks.

**Comment by maranda** [comment]
The project site.
