### ISSUE TITLE
Will MAM for MUCs be implemented?

### ISSUE THREAD

**Issue by j12i** [maranda/metronome#543]
Hey, I was looking into running a Metronome server, and I saw [here](https://compliance.conversations.im/server/lightwitch.org/) that support for MAM in MUCs is missing (supposed this is true for Metronome and not just your instance).
Is this planned to be implemented?

**Comment by maranda** [comment]
It's implemented... Just from 2017..?

**Comment by j12i** [comment]
Sorry I was just going off what lightwitch.org offered… I didn't see an explicit confirmation on the website.

**Comment by j12i** [comment]
Thanks!
(The [last commit](https://github.com/iNPUTmice/caas/commits/master) to it was just a year ago, though.)

**Comment by maranda** [comment]
The test suite just has a dumb logic atm, where if it can't create a room it'll just plainly fail the test. Which is why it's unreliable and it was also deprecated by its own maintainer.
