### ISSUE TITLE
MUC doesn't send empty subject on join

### ISSUE THREAD

**Issue by Ppjet6** [maranda/metronome#544]
Version: 3.14.5? (provided by ynh)

# What happens
When joining a MUC where no subject is configured, no `<subject/>` is sent back during join.

# Expected behaviour
A message with an empty <subject/> is sent.

This is actually a useful marker for clients to be able to differenciate historical messages and live messages. It's a MUST (SHALL) in the spec.

https://xmpp.org/extensions/xep-0045.html#enter-subject
> it SHALL send the current room subject.
> If there is no subject set, the room MUST return an empty <subject/> element. The `<delay/>` SHOULD be included if the subject was actively cleared and MAY be omitted if the room never had a subject set.

**Comment by Ppjet6** [comment]
It seems metronome doesn't send a subject at all?

I'm trying to join the room again and I don't see any `<subject/>` in the console, so my client keeps spinning.

**Comment by maranda** [comment]
Beside that the version you're describing is very old and probably the one in YuNoHost, which I pushed several PRs to get updated but alas...
That's not how the code works -> https://github.com/maranda/metronome/blob/master/plugins/muc/muc.lib.lua#L252

**Comment by Neustradamus** [comment]
@Ppjet6: @alexAubin has updated YunoHost Metronome IM:
- https://github.com/YunoHost/metronome
