### ISSUE TITLE
Respect XEP-0313: Message Archive Management

### ISSUE THREAD

**Issue by Neustradamus** [maranda/metronome#91]
Please respect XEP-0313: Message Archive Management
http://xmpp.org/extensions/xep-0313.html

There is not:
urn:xmpp:mam:0

Not official: https://code.frenchtouch.pro/valerian.saliou/xmpp/blob/master/extensions/xep-0313.xml

**Comment by tristan-k** [comment]
What modifications are necessary to make jappix compatible to prosody or the otherway around?
